language: python
python:
- "3.6"
install:
- pip install .
- pip install coverage
script:
- python -m unittest discover
- coverage run --source=. -m unittest discover
after_success: coverage report -m
